<h2>View Account</h2>
  <div id="record">  
    <table class="hovertable">
      <tr>
        <th class="key">Account ID:</th>
        <td class="value">
          <?php echo $this->escape($this->item['UserName']); ?>
        </td>
      </tr>
      <tr>
        <th class="key">First Name:</th>
        <td class="value">
          <?php echo $this->escape($this->item['FirstName']); ?>
        </td>
      </tr>
      <tr>
        <th class="key">Last Name:</th>
        <td class="value">
          <?php echo $this->escape($this->item['LastName']); ?>
        </td>
      </tr>
           <tr>
        <th class="key">Email:</th>
        <td class="value">
          <?php echo $this->escape($this->item['Email']); ?>
        </td>
      </tr>
      <tr>
        <th class="key">username:</th>
        <td class="value">
          <?php echo $this->escape($this->item['UserName']); ?>
        </td>
      </tr>
      <tr>
        <th class="key">password:</th>
        <td class="value">
          <?php echo $this->escape($this->item['Password']); ?>
        </td>
      </tr>
    </table>
  </div>  

