<h2>List Accounts</h2>
<?php if(count($this->records)): ?>
<div id="pager">Pages: <?php echo $this->pages; ?></div>
<div id="record">
	<form method="post" action="<?php echo $this->url(array(), 'admin-account-delete'); ?>">  
    <table class="hovertable">
      <tr>
      	<th></th>
        <th class="key">Account ID</th>
        <th class="key">First Name</th>
        <th class="key">Last Name</th>
        <th class="key">Email</th>
        <th class="key">username</th>
        <th class="key">password</th>
        <th></th>
        <th></th>
      </tr>
      <?php foreach ($this->records as $r): ?>
      <tr onmouseover="this.style.backgroundColor='#ffff66';" onmouseout="this.style.backgroundColor='#E4EFF1';">
      	<td><input type="checkbox" name="ids[]" value="<?php echo $r['id']; ?>" style = "width:20px" /></td>
      	<td><?php echo $this->escape($r['UserID']); ?></td>
      	<td><?php echo $this->escape($r['FirstName']); ?></td>
      	<td><?php echo $this->escape($r['LastName']); ?></td>
      	<td><?php echo $this->escape($r['Email']); ?></td>
      	<td><?php echo $this->escape($r['UserName']); ?></td>
      	<td><?php echo $this->escape($r['Password']); ?></td>
      	<td><a href="<?php echo $this->url(array('id' => $r['UserID']), 'admin-account-display'); ?>">Display</a></td>
      	<td><a href="<?php echo $this->url(array('id' => $r['UserID']), 'admin-account-update'); ?>">Update</a></td>
      	</tr>
      	<?php endforeach; ?>
      	<tr>
      		<td colspan="9"><input type="submit" name ="submit" style="width:150px" value="Delete Selected" /></td>
      	</tr>
    </table>
    </form>
</div>
<div id="pager">Pages: <?php echo $this->pages; ?></div>

<?php else: ?>No records found<?php endif; ?>