<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
    <title>SOAP Test</title>
   </head>
<body>
  
<table>
	<tr>
		<th>resutl 1:</th>
		<td><?php echo $this->result1; ?></td>
	</tr>
	<tr>
		<th>result 2:</th>
		<td><?php echo $this->result2; ?></td>
	</tr>
	<tr>
		<th>result 3:</th>
		<td><?php echo $this->result3; ?></td>
	</tr>
</table>
</body>
</html>