<h2>List Videos</h2>
<?php if(count($this->records)): ?>
<div id="pager">Pages: <?php echo $this->pages; ?></div>
<div id="record">
	<form method="post" action="<?php echo $this->url(array(), 'admin-catalog-delete'); ?>">  
    <table class="hovertable">
      <tr>
      	<th></th>
        <th class="key">Video ID</th>
        <th class="key">Uploaded by</th>
        <th class="key">Title</th>
        <th class="key">Description</th>
        <th></th>
        <th></th>
      </tr>
      
      <?php foreach ($this->records as $r): ?>
      <tr onmouseover="this.style.backgroundColor='#ffff66';" onmouseout="this.style.backgroundColor='#E4EFF1';">
      	<td><input type="checkbox" name="ids[]" value="<?php echo $r['VideoID']; ?>" style = "width:20px" /></td>
      	<td><?php echo $this->escape($r['VideoID']); ?></td>
      	<td><?php echo $this->escape($r['UserName'])?></td>
      	<td><?php echo $this->escape($r['Title']); ?></td>
      	<td><?php echo $this->escape($r['Description']); ?></td>
      	<td><a href="<?php echo $this->url(array('id' => $r['VideoID']), 'admin-catalog-display'); ?>">Display</a></td>
      	<td><a href="<?php echo $this->url(array('id' => $r['VideoID']), 'admin-catalog-update'); ?>">Update</a></td>
      	</tr>
      	<?php endforeach; ?>
      	<tr>
      		<td colspan="4"><input type="submit" name="submit" style="width:150px" value="Delete Selected" /></td>
        	<td colspan="2"><a href="<?php echo $this->url(array(), 'admin-fulltext-index-create'); ?>">Update full-text indices</a></td>
      	</tr>
    </table>
    </form>
</div>
<div id="pager">Pages: <?php echo $this->pages; ?></div>

<?php else: ?>No records found<?php endif; ?>